### ISSUE TITLE
Possibility to use tinygsm object in asyncmqttclient?

### ISSUE THREAD

**Issue by ortegafernando** [khoih-prog/AsyncMQTT_Generic#2]
Is there any possibility to use TinyGSM object in asyncmqttclient instead of "wifi" ?
Thanks.

**Comment by khoih-prog** [comment]
It's possible, but I don't have time and interest to spend on this GSM enhancement. Your contribution is always welcome.

Next time, please put in the new `Discussion`, not `Issues` section.
