### ISSUE TITLE
I can´t install library in platformio. Error to get ESPAsyncTCP

### ISSUE THREAD

**Issue by hardmax** [khoih-prog/AsyncMQTT_Generic#28]
Hi,

when I install librery in platformio appear this error:

Library Manager: Installing git+https://github.com/khoih-prog/ESPAsyncTCP
git version 2.34.0.windows.1
Cloning into 'C:\Users\msanc\.platformio\.cache\tmp\pkg-installing-qo24k_s0'...
fatal: invalid branch name: init.defaultBranch =
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/khoih-prog/ESPAsyncTCP', 'C:\\Users\\msanc\\.platformio\\.cache\\tmp\\pkg-installing-qo24k_s0']

This appear to be that deafultBranch is inexsitent in ESPAsyncTCP proyect

Platform.io version 6.1.5
* `ESP32` v2.0.5
* OS WIndows 11

Regards

**Comment by khoih-prog** [comment]
Hi @hardmax 

I have no issue installing here. You can post on PIO Forum for help, certainly with all the settings, such as `platformio.ini`, etc.

```
$ pio pkg install --global -l "khoih-prog/AsyncMQTT_Generic"
Library Manager: Installing khoih-prog/AsyncMQTT_Generic
Unpacking  [####################################]  100%
Library Manager: AsyncMQTT_Generic@1.8.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: AsyncTCP@1.1.1 is already installed
Library Manager: Installing git+https://github.com/khoih-prog/ESPAsyncTCP
git version 2.39.1
Cloning into '/home/kh/.platformio/.cache/tmp/pkg-installing-z94g0l_z'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 54 (delta 3), reused 33 (delta 2), pack-reused 0
Receiving objects: 100% (54/54), 49.41 KiB | 1.54 MiB/s, done.
Resolving deltas: 100% (3/3), done.
Library Manager: ESPAsyncTCP@1.3.0+sha.c313d96 has been installed!
Library Manager: AsyncTCP_SSL@1.3.1 is already installed
Library Manager: Portenta_H7_AsyncTCP@1.4.0 is already installed
Library Manager: Teensy41_AsyncTCP@1.1.0 is already installed
Library Manager: AsyncTCP_RP2040W@1.1.0 is already installed
Library Manager: ESPAsync_WiFiManager@1.15.1 is already installed
Library Manager: Installing me-no-dev/ESPAsyncTCP @ >=1.2.2
Unpacking  [####################################]  100%
Library Manager: ESPAsyncTCP@1.2.2 has been installed!
Library Manager: ESP Async WebServer@1.2.3 is already installed
```

Using PIO, you must be very familiar with it to **manually modify the settings as necessary.**

Good Luck,

**Comment by hardmax** [comment]
Hi, with PIO the same error:

PS C:\Users\msanc\OneDrive\Documentos\PlatformIO\Projects\Prueba> pio pkg install --global -l "khoih-prog/AsyncMQTT_Generic"
Library Manager: Installing khoih-prog/AsyncMQTT_Generic
Unpacking  [####################################]  100%
Library Manager: AsyncMQTT_Generic@1.8.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing me-no-dev/AsyncTCP @ >=1.1.1
Unpacking  [####################################]  100%
Library Manager: AsyncTCP@1.1.1 has been installed!
Library Manager: Installing git+https://github.com/khoih-prog/ESPAsyncTCP
git version 2.34.0.windows.1
Cloning into 'C:\Users\msanc\.platformio\.cache\tmp\pkg-installing-s656vqv_'...
fatal: invalid branch name: init.defaultBranch = 
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/khoih-prog/ESPAsyncTCP', 'C:\\Users\\msanc\\.platformio\\.cache\\tmp\\pkg-installing-s656vqv_']

Maybe somthing in my cache,I going to review, anyway this is my platformio settings:

[env]
upload_speed = 921600
lib_compat_mode = strict
lib_ldf_mode = chain+


[env:ESP32]
platform = espressif32
framework = arduino
lib_deps = 
    khoih-prog/AsyncMQTT_Generic@>=1.8.0

board = esp32doit-devkit-v1

Regards

**Comment by hardmax** [comment]
Hi,

I solve it. My windows Git dont have master branch. I solved put in a terminal:

git config --global init.defaultBranch master

Thansk, regards
