### ISSUE TITLE
Documentation update is needed - which MQTT versions are supported

### ISSUE THREAD

**Issue by elcreator** [khoih-prog/AsyncMQTT_Generic#4]
### Describe the bug
Documentation lacks info about which MQTT protocol versions are supported - 3.0, 3.1.1 or 5.0.

**Comment by khoih-prog** [comment]
According to [**Features**](https://github.com/marvinroger/async-mqtt-client#features) of the [**async-mqtt-client** library](https://github.com/marvinroger/async-mqtt-client) this library is based upon, 

## Features

* **Compliant with the 3.1.1 version of the protocol**
* Fully asynchronous
* Subscribe at QoS 0, 1 and 2
* Publish at QoS 0, 1 and 2
* SSL/TLS support
