### ISSUE TITLE
mqtt connection with clientid, username and password

### ISSUE THREAD

**Issue by darkcurrent** [khoih-prog/AsyncMQTT_Generic#6]
Hello, this is a very cool library. But I am little bit confused about how to set clientid, username and password for mqtt connection. Could you help me please?

**Comment by NotrinoResearch** [comment]
> Hi,
> 
> Thanks for using the library and your nice words.
> 
> Normally, the **username / password** are required only by certain MQTT Broker. clientID is generated automatically by the library using MAC address, ESP chipID, etc.
> 
> If those are required, follow these steps
> 
> 1. For **username / password**, you can use function `setCredentials(username, password)` as defined in
> 
> https://github.com/khoih-prog/AsyncMQTT_Generic/blob/9bc9c19c5cc55b960b002f14b7fc252a30e1d855/src/AsyncMqttClient_Generic_Impl.h#L253-L259
> 
> 2. For **clientID**, use function `setClientId(clientId)` as defined in
> 
> https://github.com/khoih-prog/AsyncMQTT_Generic/blob/9bc9c19c5cc55b960b002f14b7fc252a30e1d855/src/AsyncMqttClient_Generic_Impl.h#L224-L229
> 
> If not using `setClientId()`, the **clientID** will be auto-created
> 
> As this is not a bug of the library, I'm closing the issue now and suggest next time, post on [**Discussions**](https://github.com/khoih-prog/AsyncMQTT_Generic/discussions) or Arduino Forum to get help.
> 
> Good Luck,

Thank you.
